
call:
	go run main.go --to lipeng  --local-addr 172.20.30.76:15161  --protocol udp --server-addr 172.20.50.121:5060

call-aliyun:
	go run main.go  --to 13900000001  --local-addr 192.168.50.111:25161 --protocol tls --server-addr sh-sip.ccc.aliyuncs.com:8443