run-local:
	go run main.go --to lipeng  --local-addr 172.20.30.57:15060 --protocol udp --server-addr 172.20.30.57:25060

run-92:
	go run main.go --to lipeng  --local-addr 172.20.30.57:15060  --protocol udp --server-addr 172.20.30.92:5060

call:
	go run main.go --to lipeng  --local-addr 172.20.30.57:15060  --protocol udp --server-addr 172.20.50.12:5060